server:
  port: 8081

oauth2:
  client-id: 'client'

spring:
  application:
    name: rangiffler-gateway
  profiles:
    active: local
  graphql:
    graphiql:
      enabled: true
      props:
        resources:
          version: "2.4.7"  # Явно указываем версию
          query: default-query.graphql
        variables:
          editorTheme: "light"
      cdn:
        enabled: false
    schema:
      introspection:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9001'
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/rangiffler-gateway?serverTimezone=UTC&createDatabaseIfNotExist=true'
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: rangiffler-gateway
    locations: classpath:db/migration/rangiffler-gateway
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        generate_statistics: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG
    guru.qa.rangiffler: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


rangiffler-userdata:
  client: grpc

rangiffler-geo:
  client: grpc


---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9001'
  graphql:
    graphiql:
      enabled: true
grpc:
  client:
    grpcUserdataClient:
      address: 'static://localhost:8089'
      negotiationType: PLAINTEXT
    grpcGeoClient:
      address: 'static://localhost:8086'
      negotiationType: PLAINTEXT

rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
rangiffler-gateway:
  base-uri: 'http://127.0.0.1:8081'
rangiffler-userdata:
  base-uri: 'http://127.0.0.1:8088'