server:
  port: 8081

oauth2:
  client-id: 'client'

spring:
  application:
    name: rangiffler-gateway
  profiles:
    active: local
  graphql:
    graphiql:
      enabled: true
      props:
        resources:
          version: "2.4.7"  # Явно указываем версию
          query: default-query.graphql
        variables:
          editorTheme: "light"
      cdn:
        enabled: false
    schema:
      introspection:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9001'

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.transaction: DEBUG
    ru.sentidas.rangiffler: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


rangiffler-userdata:
  client: grpc

rangiffler-geo:
  client: grpc


---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9001'
  graphql:
    graphiql:
      enabled: true
grpc:
  client:
    grpcUserdataClient:
      address: 'static://localhost:8087'
      negotiationType: PLAINTEXT
      max-inbound-message-size: 10485760   # 10 MB
    grpcGeoClient:
      address: 'static://localhost:8086'
      negotiationType: PLAINTEXT
    grpcPhotoClient:
      address: 'static://localhost:8095'
      negotiationType: PLAINTEXT
      max-inbound-message-size: 26214400   # 25 MB
rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
rangiffler-gateway:
  base-uri: 'http://127.0.0.1:8081'
rangiffler-userdata:
  base-uri: 'http://127.0.0.1:8088'
rangiffler-geo:
  base-uri: 'http://127.0.0.1:8085'
rangiffler-photo:
  base-uri: 'http://127.0.0.1:8094'