server:
  port: 8088

grpc:
  server:
    port: 8087

spring:
  application:
    name: rangiffler-userdata
  profiles:
    active: local
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: rangiffler-userdata
    locations: classpath:db/migration/rangiffler-userdata
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    open-in-view: false

logging:
  file:
    path: ./logs/rangiffler-userdata
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.boot.autoconfigure: INFO
    ru.sentidas.rangiffler: DEBUG
    io.grpc : INFO
    net.devh.boot.grpc.server: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/rangiffler-userdata?serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: root
    password: root
rangiffler-geo:
  base-uri: 'http://127.0.0.1:8085'
rangiffler-userdata:
  base-uri: 'http://127.0.0.1:8088'
rangiffler-photo:
  base-uri: 'http://127.0.0.1:8094'
---

