spring:
  application:
    name: event-log
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/rangiffler-event?serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: event-log
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: ru.sentidas.rangiffler.ActivityEvent
    listener:
      ack-mode: BATCH
      missing-topics-fatal: false

app:
  activity-topic: rangiffler_activity

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://rangiffler-all-db:3306/rangiffler-event?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

app:
  activity-topic: rangiffler_activity